apiVersion: v1
kind: Namespace
metadata:
  name: postgres-reverse-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-reverse-proxy-deployment
  namespace: postgres-reverse-proxy
  labels:
    app: postgres-reverse-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-reverse-proxy
  template:
    metadata:
      labels:
        app: postgres-reverse-proxy
    spec:
      containers:
        - name: postgres-reverse-proxy
          image: petcompufrgs/postgresql-server-proxy:2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reverse-proxy-service
  namespace: postgres-reverse-proxy
spec:
  selector:
    app: postgres-reverse-proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: postgres-reverse-proxy-ingress
  namespace: postgres-reverse-proxy
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  backend:
    serviceName: 'postgres-reverse-proxy-service'
    servicePort: 80
  rules:
    - host: 'postgresql.petcompufrgs.tk'
---