FROM debian:stable-slim

RUN apt update && \ 
    apt -y upgrade && \
    mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 && \
    apt install openjdk-11-jdk -y && \
    apt install openjdk-11-jre -y